### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by tgoodbody** [tgoodbody/caRlo#1]
## Sampling & Stats
- [x] Write sampling functions
- [x] Write statistics calculation functions
- [x] Write statistical analysis functions
- [x] Write visualization functions

## ALS

- [ ] Download ALS datasets

## GEDI

- [ ] Write download + filtering + extract
- [ ] Make GEDI & ALS metrics the same names

## General

- [x] Plan list of functions to include in package
- [x] Determine which sampling methodologies to include
- [ ] Determine statistics we want to use for analysis
- [x] Determine which site(s) to use as tests
- [ ] Determine which sites to use for full analysis

## Data Types to process

- GEDI
- ALS

## Sites to process

- Canada: Romeo Mallette, Newfoundland?, New Brunswick?

## Statistics to use

- Which estimators to use
    - Mean, quantiles, variation
    - standard error
    - number of montecarlo simulations to run: https://stats.stackexchange.com/questions/28987/calculate-number-of-needed-simulations

## expected outputs

- Site level comparison of GEDI (sample) vs ALS (population)
    - Population parameter estimates (by sample size, sampling approach, site) with standard errors
    - Visualized distributions of above
